name: Self-Hosted Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display hostname
        run: hostname

      - name: Display OS info
        run: uname -a

      - name: List working directory
        run: ls -la
